name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -o meba-linux-amd64 ./cmd/meba
        GOOS=darwin GOARCH=amd64 go build -o meba-darwin-amd64 ./cmd/meba
        GOOS=darwin GOARCH=arm64 go build -o meba-darwin-arm64 ./cmd/meba
        GOOS=windows GOARCH=amd64 go build -o meba-windows-amd64.exe ./cmd/meba
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          meba-linux-amd64
          meba-darwin-amd64
          meba-darwin-arm64
          meba-windows-amd64.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}